//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF0605
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
    
        [JsonIgnore]
        public virtual Country Country { get; set; }
    }
}
